micronaut:
  server:
    port: 8090
  application:
    name: store

datasources:
  default:
    url: jdbc:mysql://localhost:3306/tesco
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 'tesco-rules'
    schema-generate: CREATE_DROP
    dialect: MYSQL
jpa.default.properties.hibernate.hbm2ddl.auto: update
